### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sekikazuya** [sekikazuya/furima-36569#22]
# URL
https://furima-36569.herokuapp.com/
# Basic認証のIDとパスワード
- ID:：furima
- パスワード：36569
# 出品者用のメールアドレスとパスワード
- メールアドレス：aaa@aa.com
- パスワード：aaa111
# 購入者用のメールアドレスとパスワード
- メールアドレス：bbb@bb.com
- パスワード：bbb222

**Comment by takumi0530** [comment]
@sekikazuya さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **配送料の負担は、「---、着払い(購入者負担)、送料込み(出品者負担)」の3項目が表示されること（--- は初期値として設定すること）**
「送料込み(出品者負担)」の「）」がありませんでした。ご確認をお願いいたします。
<img width="300" alt="スクリーンショット 2021-09-16 17 50 33" src="https://user-images.githubusercontent.com/76197191/133582016-5b2646bf-fff5-4752-ab03-ac87c6e6b56e.png">

- [ ] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
情報を全て埋めて購入ボタンを押した際に、エラーページに遷移してしまい、購入ができませんでした。
**※上記により、購入機能と売却後の商品の動作確認ができておりません。次回ご提出時に確認させていただきます。**
<img width="549" alt="スクリーンショット 2021-09-16 17 56 58" src="https://user-images.githubusercontent.com/76197191/133582748-d8c80b5e-f0c9-4223-96b0-f70cb3cedc96.png">



修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sekikazuya** [comment]
レビューありがとうございます！
ご指摘いただいた内容を修正致しましたので再度レビューいただけないでしょうか。
よろしくお願いいたします。

**Comment by takumi0530** [comment]
@sekikazuya さん、お待たせいたしました。フリマアプリ達成要件分の開発お疲れ様でした！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

**＜今後の学習例＞**
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

**＜提出物＞**
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

**＜最終課題に関する締め切りについての動画＞**
`https://master.tech-camp.in/v2/curriculums/6852`

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/133707940-6c391c6b-ebb0-4f44-a882-7b6114bbc1d0.png)
